### ISSUE TITLE
services model: `attributes` definition not so clear

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.IssueTracking#9]
Hi, 
in the `services` model (https://github.com/smart-data-models/dataModel.IssueTracking/blob/master/services/model.yaml) the `attributes` definition looks like:

```
attributes:
      description: "As per the [Service Definition](http://wiki.open311.org/GeoReport_v2/#get-service-definition) structure defined by Open 311."
      items:
        anyOf:
          - type: string
          - type: object
          - type: array
          - type: boolean
          - type: number
      type: array
      x-ngsi:
        type: Property
```
which is not very clear, in my opinion, and it does not make extracting the model information very easy.
Looking at the mentioned link in the description I can see, as an example, something like:

```
{
  "service_code":"DMV66",
  "attributes":[
    {
      "variable":true,
      "code":"WHISHETN",
      "datatype":"singlevaluelist",
      "required":true,
      "datatype_description":null,
      "order":1,
      "description":"What is the ticket/tag/DL number?",
      "values":[
        {
          "key":123,
          "name":"Ford"
        },
        {
          "key":124,
          "name":"Chrysler"
        }
      ]
    }
  ]
}
```
Would it be possible to update the model definition accordingly?
Something like:
```
attributes:
   description: "As per the [Service Definition](http://wiki.open311.org/GeoReport_v2/#get-service-definition) structure defined by Open 311."
   type: array
   items: 
        type: object
        properties:
              variable:
                 type:  boolean
              code: 
                  type: string
              datatype:
                   type: string
              required:
                    type: boolean
              datatype_description: 
                     type: string
              order:
                      type: number
             description:
                       type: string
             values:
                  type: array
                  items:
                       type: object
                       properties:
                             key: 
                                type: number
                             name:
                                 type: string
```
I think this would make it easier to understand the model and to get easy access to its structure.

Thanks!
